modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/rhysdh540/create-ntl/issues"
license = "GNU GPLv3"

[[mods]]
modId = "notrainlimits"
version = "${version}"
displayName = "Create NTL"
authors = "rdh"
description = '''
Allows players to place illegal train tracks in Create
'''
logoFile = "icon.png"

[[dependencies.notrainlimits]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.notrainlimits]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.notrainlimits]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"