modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/rhysdh540/create-unlimited/issues"
license = "GNU GPLv3"

[[mods]]
modId = "createunlimited"
version = "${version}"
displayName = "Create Unlimited"
authors = "rdh"
description = '''
Remove all the limits!
'''
logoFile = "icon.png"

[[dependencies.createunlimited]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createunlimited]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createunlimited]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"