name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting, make sure that:
          - You are using the latest version of the mod.
          - You are using the recommended version of Create.
          - You are using the correct version of Minecraft (and the right mod loader).
          - The issue does not occur in without Create Unlimited installed.
        
        **Do not forget to give your issue a descriptive title.** "game crashes" makes it hard to distinguish issues at a glance.
  - type: dropdown
    attributes:
      label: Minecraft Mod Loader
      description: If you know this bug occurs on multiple loaders, select all you have tested.
      multiple: true
      options:
        - Forge
        - Fabric
        - Quilt
  - type: textarea
    attributes:
      label: Minecraft Version
      description: The version of Minecraft used in the bug report.
      placeholder: 1.18.2
    validations:
      required: true
  - type: textarea
    attributes:
      label: Mod Version
      description: The version of Create Unlimited used in the bug report.
      placeholder: 0.2
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of bug
      description: What did you expect to happen, what happened, and why is it incorrect?
      placeholder: My train disappears when i drive around sharp corners!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: A bulleted list, or an exported instance if relevant.
      placeholder: "* drive a long train around a sharp corner"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suspected cause
      description: If you know what could be causing this bug, describe it here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: This issue is unique
      options:
        - label: I have searched the issue tracker and did not find an issue describing my bug.
          required: true