name: Suggestion
description: Suggest a feature for NTL
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature for NTL!
        Please, before submitting, make sure that:
          * You are using the latest version of the mod.
          * Your suggestion is not already in the issue tracker.
  - type: textarea
    attributes:
      label: Description of feature
      description: What do you want to exist in NTL?
      placeholder: I want flying trains!
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: This suggestion is unique
      options:
        - label: I have searched the issue tracker and did not find an existing suggestion describing my feature.
          required: true